version: '3.8'
services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb-http-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  app:
    build:
      context: .
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_LOG=${SERVER_LOG}
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  data: