version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-http-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5


  mongo-express:
    image: mongo-express
    ports: 
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      mongodb:
        condition: service_healthy
  app:
    build:
      context: .
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - SERVER_PORT=${SERVER_PORT}
      - LOGFILE=${LOGFILE}
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  data: